Repository michaeljones/breathe, pull requests merged in 2018-06, with the labels that each got.

#380 Render newlines as separate paragraphs
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#382 Don't append separator for paragraph type.
  breathe/renderer/sphinxrenderer.py
Labels: bug, code, regression

#385 explicitly use sphinx 1.7.5 for ci/dev
  .travis.yml
  README.rst
Labels: analysis
