Repository michaeljones/breathe, pull requests merged in 2019-04, with the labels that each got.

#411 Adapt to upcoming Sphinx 2.0
  .travis.yml
  breathe/renderer/sphinxrenderer.py
  tests/test_renderer.py
Labels: code, test

#428 Add support for rendering parameter direction information
  breathe/parser/compoundsuper.py
  examples/doxygen/func.h
Labels: code, enhancement

#432 pkg: drop support for python 2, require sphinx>=2.0
  setup.cfg
  setup.py
Labels: regression
