Repository michaeljones/breathe, pull requests merged in 2020-12, with the labels that each got.

#602 Fix anchors on pages generated by Doxygen>=1.8.17
  breathe/parser/compound.py
Labels: bug, code, regression

#603 Add support for \parblock parsing and rendering
  breathe/parser/compound.py
  breathe/parser/compoundsuper.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/doxygen.rst
  examples/doxygen/.gitignore
  examples/doxygen/Makefile
  examples/doxygen/parblock.cfg
  examples/doxygen/parblock.cpp
Labels: code, enhancement

#606 Allow lookup in doxygenfunction without writing param names
  breathe/directives.py
  tests/data/arange.xml
  tests/test_renderer.py
Labels: bug, code, regression, test

#609 Addendum to #606, for functions with '...'
  breathe/directives.py
Labels: bug, code, regression
