Repository michaeljones/breathe, pull requests merged in 2020-09, with the labels that each got.

#560 Add support for verbatim inline elements
  breathe/process.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/markups.rst
  examples/specific/rst.cfg
  examples/specific/rst.h
Labels: code, enhancement

#566 Fix wrong refid when SEPARATE_MEMBER_PAGES is YES
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/directives.rst
  tests/test_renderer.py
Labels: code, enhancement

#576 475 fix rtd build
  .readthedocs.yaml
  requirements/production.txt
Labels: bug, documentation, regression

#581 Add breathe_show_enumvalue_initializer option
  README.rst
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/directives.rst
Labels: code, enhancement

#585 Fix anonymous struct/union usage in C domain
  breathe/renderer/sphinxrenderer.py
Labels: bug, code
