Repository michaeljones/breathe, pull requests merged in 2020-08, with the labels that each got.

#550 C# Support
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/file.rst
  setup.py
Labels: enhancement

#551 Doc, fix typo, :source: -> :project:
  documentation/source/autofile.rst
  documentation/source/directives.rst
Labels: documentation

#556 Add support for innergroup
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/group.rst
  examples/specific/group.h
  tests/test_renderer.py
Labels: enhancement

#563 Avoid duplicate doxygen targets
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#564 remove Travis badge from README file
  README.rst
Labels: documentation

#567 Fix Read The Docs Build
  .readthedocs.yaml
Labels: bug, documentation, regression

#570 Note doxygenclass template specialization spacing
  documentation/source/class.rst
Labels: documentation, enhancement

#572 Reuse breathe.__version__ in setup
  setup.py
Labels: enhancement

#573 Add :inner: to the doxygengroup section
  documentation/source/directives.rst
Labels: documentation, enhancement
