Repository michaeljones/breathe, pull requests merged in 2020-03, with the labels that each got.

#474 Add GitHub actions
  .github/workflows/documentation.yml
  .github/workflows/lint.yml
  .github/workflows/unit_tests.yml
  README.rst
  requirements/production.txt
Labels: analysis, enhancement

#486 Fixes to use Sphinx 2.4.4
  .github/workflows/unit_tests.yml
  .travis.yml
  tests/test_renderer.py
Labels: analysis

#484 nose added to development requirements
  requirements/development.txt
Labels: enhancement

#487 Switch to pytest from nose
  .github/workflows/unit_tests.yml
  .travis.yml
  Makefile
  requirements/development.txt
  tests/runtests.sh
  tests/test_renderer.py
Labels: analysis, enhancement, test
