Repository michaeljones/breathe, pull requests merged in 2020-05, with the labels that each got.

#512 Scoped rendering
  breathe/renderer/__init__.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/conf.py
  documentation/source/members.rst
  documentation/source/specific.rst
  examples/doxygen/pyexample.py
  examples/specific/Makefile
  examples/specific/c_struct.h
  examples/specific/cpp_enum.cfg
  examples/specific/cpp_enum.h
  examples/specific/cpp_function.cfg
  examples/specific/cpp_function.h
  examples/specific/cpp_inherited_members.cfg
  examples/specific/cpp_inherited_members.h
  examples/specific/cpp_trailing_return_type.cfg
  examples/specific/cpp_trailing_return_type.h
  examples/specific/cpp_union.cfg
  examples/specific/cpp_union.h
  examples/specific/struct_function.h
  examples/specific/typedef.h
  tests/test_renderer.py
Labels: bug, code, enhancement, test

#517 Support titles in verbatim blocks
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#522 Fix friend class rendering and allow 'friend struct'
  breathe/renderer/sphinxrenderer.py
  documentation/source/conf.py
  documentation/source/specific.rst
  examples/specific/Makefile
  examples/specific/cpp_friendclass.cfg
  examples/specific/cpp_friendclass.h
Labels: bug, code, regression

#526 Extern examples and hax removal
  breathe/directives.py
  documentation/source/specific.rst
Labels: code, enhancement

#524 Render function candidates without using Sphinx directives
  breathe/directive/base.py
  breathe/directives.py
Labels: bug, code

#533 Make debug config variables available in conf.py
  breathe/__init__.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/conf.py
  tests/test_renderer.py
Labels: code

#535 Fix warning formatting for function lookup
  breathe/directive/base.py
  breathe/directives.py
Labels: bug, code
