Repository michaeljones/breathe, pull requests merged in 2021-03, with the labels that each got.

#637 code and documentation for membergroups and members-only options
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/class.rst
  documentation/source/conf.py
  documentation/source/directives.rst
  documentation/source/struct.rst
  examples/specific/Makefile
  examples/specific/membergroups.cfg
  examples/specific/membergroups.h
Labels: code, enhancement

#644 Minor issue: example.tag gets modified during build, add to .gitignore.
  .gitignore
Labels: packaging

#645 Add support for content-only flag when rendering pages
  breathe/directives.py
  breathe/renderer/sphinxrenderer.py
  documentation/source/directives.rst
Labels: code, enhancement

#647 When rendering a section, add target after title
  breathe/renderer/sphinxrenderer.py
Labels: bug, code, regression

#651 Render pages content in order
  breathe/parser/compound.py
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#658 Adds an id to the rubric created for each section of a group.
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#661 Add missing getter and setter for csharp
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#642 Add support for rowspan/colspan to tables
  breathe/parser/compound.py
  breathe/parser/compoundsuper.py
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement
