Repository michaeljones/breathe, pull requests merged in 2021-02, with the labels that each got.

#628 Add various specifiers to functions and variables
  breathe/renderer/sphinxrenderer.py
  tests/warnings/source/conf.py
Labels: code, enhancement

#630 Added multiply inherited class for PHP objects
  breathe/renderer/sphinxrenderer.py
  documentation/source/directives.rst
Labels: bug, code, regression

#632 Initial support for table rendering
  breathe/parser/compound.py
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#635 Add rendering of \section, \subsection and \subsubsection
  breathe/parser/compoundsuper.py
  breathe/renderer/sphinxrenderer.py
Labels: code, enhancement

#640 Sphinx 3.5 compatibility
  .github/workflows/unit_tests.yml
  requirements/production.txt
  setup.py
Labels: packaging

#639 Fix linking to sections
  breathe/renderer/sphinxrenderer.py
Labels: code

#638 Add table examples to documentation
  documentation/source/conf.py
  documentation/source/index.rst
  documentation/source/tables.rst
  examples/specific/Makefile
  examples/specific/tables.cfg
  examples/specific/tables.h
Labels: documentation
