Repository michaeljones/breathe, pull requests merged in 2021-04, with the labels that each got.

#668 Fix: C# should not have inline modifier
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#669 Use add_css_file instead of deprecated/removed add_stylesheet
  breathe/directives.py
Labels: code

#670 Use native docutils for field lists, notes, and warnings
  breathe/renderer/sphinxrenderer.py
  tests/test_renderer.py
Labels: code, enhancement

#672 Handle directives returning no nodes on error
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#675 Splice out parameter direction in field lists
  breathe/renderer/sphinxrenderer.py
Labels: bug, code, regression

#676 Fixes for Sphinx v4
  .github/workflows/unit_tests.yml
  breathe/renderer/sphinxrenderer.py
  requirements/production.txt
  setup.py
  tests/test_renderer.py
Labels: code, test

#678 Fix paragraph in paragraph rendering
  breathe/renderer/filter.py
  breathe/renderer/mask.py
  breathe/renderer/sphinxrenderer.py
  examples/tinyxml/tinyxml.h
  requirements/production.txt
Labels: bug, code

#679 doxygenfunction, strip names before lookup
  breathe/directives.py
Labels: code, enhancement

#681 When rendering template params, insert name by parsing
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#682 Remove stale six dep
  setup.py
Labels: bug, packaging

#685 Render fields with multiple names instead of crashing
  breathe/renderer/sphinxrenderer.py
Labels: bug, code, regression

#686 Start pytest via module instead of exe
  Makefile
  tests/runtests.sh
Labels: test
