Repository michaeljones/breathe, pull requests merged in 2021-01, with the labels that each got.

#610 add test for ellipsis in args
  tests/data/ellipsis.xml
  tests/test_renderer.py
Labels: test

#617 Sphinx 3.4.x compatibility
  .github/workflows/unit_tests.yml
  breathe/directives.py
  breathe/path_handler.py
  requirements/production.txt
  setup.py
Labels: packaging

#622 Fixed doxygenfile causing duplicate IDs.
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#623 doxygenfunction fixes
  breathe/directives.py
  breathe/renderer/filter.py
  breathe/renderer/sphinxrenderer.py
  tests/test_renderer.py
Labels: code, enhancement
