Repository michaeljones/breathe, pull requests merged in 2021-05, with the labels that each got.

#687 Fix retval rendering
  breathe/renderer/sphinxrenderer.py
Labels: bug, code, regression

#690 Correctly label example as C
  documentation/source/conf.py
  documentation/source/specific.rst
Labels: documentation

#694 apidoc: add -m, --members option flag
  .github/workflows/documentation.yml
  breathe/apidoc.py
Labels: code, enhancement

#697 Collapse multiple retvals into a single bullet list
  breathe/renderer/sphinxrenderer.py
Labels: code
