Repository michaeljones/breathe, pull requests merged in 2021-09, with the labels that each got.

#741 cicd: track sphinx 4.2.x development series
  .github/workflows/unit_tests.yml
  CHANGELOG.rst
Labels: analysis

#737 Fix sphinxrenderer.py variable and function visitors for C#
  breathe/renderer/sphinxrenderer.py
Labels: bug, code

#729 Add breate_doxygen_aliases config value
  CHANGELOG.rst
  breathe/directives/setup.py
  breathe/process.py
  documentation/source/directives.rst
Labels: enhancement, code
